# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name:  Prepare
        run: |
          sudo apt-get update
          sudo apt install -y gcc, npm, libwebkit2gtk-4.0-dev curl, gcc python3 
          export CHOOSENIM_NO_ANALYTICS=1
          curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
          export PATH=$HOME/.nimble/bin:$PATH
          choosenim ${{ matrix.nim-channel }}

      # Runs a set of commands using the runners shell
      - name: Test
        run: |
          export PATH=$HOME/.nimble/bin:$PATH
          nim --version
          nimble test
          # npm run build --prefix examples/svelte
          # npm run build --prefix examples/vue
